### ISSUE TITLE
Allow custom label elements in form-control-has-label

### ISSUE THREAD

**Issue by gavmck** [vue-a11y/eslint-plugin-vuejs-accessibility#333]
We have custom label components. 
Currently the `label-has-for` rule supports custom components to validate as labels. 
We need to update the `form-control-has-label` rule to accept custom label definitions.

**Comment by gavmck** [comment]
PR open with a fix for this one: https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/pull/334

**Comment by vhoyer** [comment]
I Don't have an ETA yet as I still don't have access to the npm. Tho Kevin said he would make it so I could release :) I don't think I have access yet since I don't see the package in my npm packages page, but I can try today make a release, if it works, it works if it doesn't, then we will be waiting for a little longer :)

**Comment by kddnewton** [comment]
Sorry @vhoyer just added you

**Comment by vhoyer** [comment]
it's released! :tada: will close this here, feel free to reopen or create a new issue if there is anything wrong ;D
