### ISSUE TITLE
Elements with the "tablist" interactive role must be focusable

### ISSUE THREAD

**Issue by jcupps** [vue-a11y/eslint-plugin-vuejs-accessibility#416]
Hello, I think the `interactive-supports-focus` rule is being applied incorrectly to the "tablist" role. According to the ARIA spec, while child elements with the "tab" role should be focusable, there is no indication that the containing "tablist" element must be focusable.

**Comment by jcupps** [comment]
@vhoyer As I understand it's recommended to move focus into the `tabpanel` after a tab is activated. `tablist` is just a container for `tabs`, which themselves should be focusable.
https://www.w3.org/TR/wai-aria-1.2/#tablist

**Comment by vhoyer** [comment]
I think I get it, the thing is that a `tabpanel` is a `composite` `widget`. WAI-ARIA has this to say about composite widgets:

> Authors SHOULD ensure that a composite widget exists as a single navigation stop within the larger navigation system of the web page. Once the composite widget has focus, authors SHOULD provide a separate navigation mechanism for users to navigate to [elements](https://www.w3.org/TR/wai-aria-1.2/#dfn-element) that are descendants or owned children of the composite element.

So I guess it's kind of a gray area whether we have them focusable or not, because I guess it depends on the implementation, that said, non of the example provided by the wai aria practices have the `tablist` focusable, so I guess you are right, I guess we should ignore `composite` roles when checking for focusable elements.

I was also checking the implementation of the jsx library, and the implementation there is the same here. As a workaround I guess you could add a `tabindex="-1"`

reference:
https://www.w3.org/TR/wai-aria-1.2/#tablist
https://www.w3.org/TR/wai-aria-1.2/#composite
https://www.w3.org/TR/wai-aria-1.2/#managingfocus
https://www.w3.org/TR/2021/NOTE-wai-aria-practices-1.2-20211129/examples/tabs/tabs-1/tabs.html
https://www.w3.org/TR/2021/NOTE-wai-aria-practices-1.2-20211129/examples/tabs/tabs-2/tabs.html
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/src/rules/interactive-supports-focus.js

**Comment by jcupps** [comment]
BTW I just realized that I only get this warning when I add a handler for certain events, such as "key<up|down|press>" and "click", to the element with the "tablist" role. It works for my use case because the event bubbles from child elements that are focusable.

**Comment by vhoyer** [comment]
oh, in that case the rule is doing it's job correctly, and you should skip this instance where to you this is not completely relevant, or add the `tabindex` workaround, just keep in mind to make the children `tab`s tabbable for accessibility through the keyboard, I'd recommend closing the issue :D
